/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasiresepmasakan;

/**
 *
 * @author Ahurrez
 */
public class MenuUtamaFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtamaFrame
     */
    public MenuUtamaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TJudul = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABahan = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TAPengerjaan = new javax.swing.JTextArea();
        BSimpanData = new javax.swing.JButton();
        BMulaiUlang = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        CBAlatMasak = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        TDataResep = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        BSimpanUlang = new javax.swing.JButton();
        BModifikasi = new javax.swing.JButton();
        BMenghapus = new javax.swing.JButton();
        BPindaiData = new javax.swing.JButton();
        BCetakData = new javax.swing.JButton();
        BCetak = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        BKeluarMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 50, 70));

        jLabel2.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(220, 240, 255));
        jLabel2.setText("\"Masukan Resep Masakan\"");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(220, 240, 255));
        jLabel5.setText("Silahkan Isi Data-data yang di Minta :");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(220, 240, 255));
        jLabel6.setText("Judul Masakan :");

        TJudul.setBackground(new java.awt.Color(50, 70, 100));
        TJudul.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        TJudul.setForeground(new java.awt.Color(255, 255, 255));
        TJudul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(220, 240, 255));
        jLabel7.setText("Bahan-bahan :");

        TABahan.setBackground(new java.awt.Color(50, 70, 100));
        TABahan.setColumns(20);
        TABahan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        TABahan.setForeground(new java.awt.Color(255, 255, 255));
        TABahan.setRows(5);
        TABahan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        jScrollPane1.setViewportView(TABahan);

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(220, 240, 255));
        jLabel8.setText("Tahap Pengerjaan :");

        TAPengerjaan.setBackground(new java.awt.Color(50, 70, 100));
        TAPengerjaan.setColumns(20);
        TAPengerjaan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        TAPengerjaan.setForeground(new java.awt.Color(255, 255, 255));
        TAPengerjaan.setRows(5);
        TAPengerjaan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        jScrollPane2.setViewportView(TAPengerjaan);

        BSimpanData.setBackground(new java.awt.Color(50, 70, 100));
        BSimpanData.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BSimpanData.setForeground(new java.awt.Color(255, 255, 255));
        BSimpanData.setText("Simpan Data");
        BSimpanData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        BMulaiUlang.setBackground(new java.awt.Color(50, 70, 100));
        BMulaiUlang.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BMulaiUlang.setForeground(new java.awt.Color(255, 255, 255));
        BMulaiUlang.setText("Mulai Ulang");
        BMulaiUlang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(220, 240, 255));
        jLabel9.setText("Alat Utama yang Digunakan :");

        CBAlatMasak.setBackground(new java.awt.Color(50, 70, 100));
        CBAlatMasak.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        CBAlatMasak.setForeground(new java.awt.Color(255, 255, 255));
        CBAlatMasak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wajan", "Panci", "Teflon", "Blender", "Kukus-san" }));
        CBAlatMasak.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        TDataResep.setBackground(new java.awt.Color(50, 70, 100));
        TDataResep.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        TDataResep.setForeground(new java.awt.Color(255, 255, 255));
        TDataResep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Judul", "Bahan-Bahan", "Tahap Pengerjaan", "Alat Utama"
            }
        ));
        jScrollPane3.setViewportView(TDataResep);

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(220, 240, 255));
        jLabel10.setText("Data Resep Masakan yang Tersimpan :");

        BSimpanUlang.setBackground(new java.awt.Color(50, 70, 100));
        BSimpanUlang.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BSimpanUlang.setForeground(new java.awt.Color(255, 255, 255));
        BSimpanUlang.setText("Simpan Ulang");
        BSimpanUlang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        BModifikasi.setBackground(new java.awt.Color(50, 70, 100));
        BModifikasi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BModifikasi.setForeground(new java.awt.Color(255, 255, 255));
        BModifikasi.setText("Modifikasi");
        BModifikasi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        BMenghapus.setBackground(new java.awt.Color(50, 70, 100));
        BMenghapus.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BMenghapus.setForeground(new java.awt.Color(255, 255, 255));
        BMenghapus.setText("Menghapus");
        BMenghapus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        BPindaiData.setBackground(new java.awt.Color(50, 70, 100));
        BPindaiData.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BPindaiData.setForeground(new java.awt.Color(255, 255, 255));
        BPindaiData.setText("Pindai Data");
        BPindaiData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        BCetakData.setBackground(new java.awt.Color(50, 70, 100));
        BCetakData.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BCetakData.setForeground(new java.awt.Color(255, 255, 255));
        BCetakData.setText("Cetak Data");
        BCetakData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        BCetak.setBackground(new java.awt.Color(50, 70, 100));
        BCetak.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BCetak.setForeground(new java.awt.Color(255, 255, 255));
        BCetak.setText("Cetak");
        BCetak.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        BKeluarMenu.setBackground(new java.awt.Color(50, 70, 100));
        BKeluarMenu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BKeluarMenu.setForeground(new java.awt.Color(255, 255, 255));
        BKeluarMenu.setText("Keluar Menu");
        BKeluarMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel2))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addGap(101, 101, 101)
                .addComponent(TJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addGap(114, 114, 114)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addGap(80, 80, 80)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(CBAlatMasak, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(448, 448, 448)
                .addComponent(BSimpanData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BMulaiUlang, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(BSimpanUlang, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BModifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BMenghapus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BPindaiData, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BCetakData, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(735, 735, 735)
                .addComponent(BKeluarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6))
                    .addComponent(TJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(CBAlatMasak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BSimpanData)
                    .addComponent(BMulaiUlang)
                    .addComponent(BCetak))
                .addGap(13, 13, 13)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel10)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BSimpanUlang)
                    .addComponent(BModifikasi)
                    .addComponent(BMenghapus)
                    .addComponent(BPindaiData)
                    .addComponent(BCetakData))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BKeluarMenu)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtamaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCetak;
    private javax.swing.JButton BCetakData;
    private javax.swing.JButton BKeluarMenu;
    private javax.swing.JButton BMenghapus;
    private javax.swing.JButton BModifikasi;
    private javax.swing.JButton BMulaiUlang;
    private javax.swing.JButton BPindaiData;
    private javax.swing.JButton BSimpanData;
    private javax.swing.JButton BSimpanUlang;
    private javax.swing.JComboBox<String> CBAlatMasak;
    private javax.swing.JTextArea TABahan;
    private javax.swing.JTextArea TAPengerjaan;
    private javax.swing.JTable TDataResep;
    private javax.swing.JTextField TJudul;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
